#!/bin/bash

# Save these steps somewhere safe and close Chrome.
# Click the "Preferences" icon in your Mac's menu bar and select "Profiles".
#Select all "AdminPrefs" profile(s) and delete it/them by clicking the minus (-) icon at the bottom.
#Once you've removed the unwanted "adminprefs" profile(s), you should be able to follow these steps:
#Open the Terminal app (Go > Utilities > Terminal or press Command+Space and search Terminal)
#Enter the commands below and hit the Enter key after each one:

defaults write com.google.Chrome HomepageIsNewTabPage -bool false
defaults write com.google.Chrome NewTabPageLocation -string "https://www.google.com/"
defaults write com.google.Chrome HomepageLocation -string "https://www.google.com/"
defaults delete com.google.Chrome DefaultSearchProviderSearchURL
defaults delete com.google.Chrome DefaultSearchProviderNewTabURL
defaults delete com.google.Chrome DefaultSearchProviderName

echo "Now restart Chrome and the issue should be resolved. If not, you may need to restart your Mac."

#https://support.google.com/chrome/thread/9350623?hl=en
